spring.application.name=agendador-tarefas

spring.mongodb.uri=mongodb://mongo:27017/db_agendador
#anotação: spring.mongodb.uri=mongodb://localhost:27017/db_agendador (para rodar na IDE)

usuario.url=usuario:8080
#anotação: usuario.url=localhost:8080 (para rodar na IDE)

server.port=8081